services:
  # Mosquitto MQTT Broker for Integration Testing
  mosquitto-test:
    image: eclipse-mosquitto:2.0
    container_name: merkle_kv_mosquitto_test
    ports:
      - "1883:1883"    # MQTT
      - "8883:8883"    # MQTT over TLS
    volumes:
      - ./test/integration/config/mosquitto:/mosquitto/config:ro
      - mosquitto_test_data:/mosquitto/data
      - mosquitto_test_log:/mosquitto/log
    environment:
      - TZ=UTC
    networks:
      - integration_test_network
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -t '$$SYS/broker/uptime' -C 1 | grep -q '[0-9]'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # HiveMQ CE MQTT Broker for Integration Testing (TLS disabled for now)
  hivemq-test:
    image: hivemq/hivemq-ce:latest
    container_name: merkle_kv_hivemq_test
    ports:
      - "1884:1883"    # MQTT (different port to avoid conflicts)
    volumes:
      - ./test/integration/config/hivemq:/opt/hivemq/conf:ro
      - hivemq_test_data:/opt/hivemq/data
      - hivemq_test_log:/opt/hivemq/log
    environment:
      - TZ=UTC
      - HIVEMQ_LOG_LEVEL=INFO
    networks:
      - integration_test_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/mqtt/clients || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Network proxy for simulating network partitions
  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.5.0
    container_name: merkle_kv_toxiproxy
    ports:
      - "8474:8474"    # Toxiproxy API
      - "1885:1885"    # Proxied Mosquitto MQTT
      - "8885:8885"    # Proxied Mosquitto MQTT/TLS
      - "1886:1886"    # Proxied HiveMQ MQTT
      - "8886:8886"    # Proxied HiveMQ MQTT/TLS
    networks:
      - integration_test_network
    depends_on:
      - mosquitto-test
      - hivemq-test

networks:
  integration_test_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  mosquitto_test_data:
    driver: local
  mosquitto_test_log:
    driver: local
  hivemq_test_data:
    driver: local
  hivemq_test_log:
    driver: local