name: merkle_kv_mobile
repository: https://github.com/AI-Decenter/MerkleKV-Mobile

packages:
  - packages/**
  - apps/**

command:
  version:
    workspaceChangelog: true
    linkToCommits: true
  bootstrap:
    runPubGetInParallel: false
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze
    exec:
      failFast: true
  
  test:
    run: dart test
    exec:
      failFast: true
  
  test:melos:dart:
    description: Run Dart tests for pure Dart packages (excluding integration tests)
    run: dart test -x integration --reporter=expanded --timeout=30s
    exec:
      failFast: true
    packageFilters:
      flutter: false
      
  test:melos:flutter:
    description: Run Flutter tests for Flutter packages
    run: flutter test --reporter=expanded --timeout=30s
    exec:
      failFast: true
    packageFilters:
      flutter: true

  test:mobile:e2e:
    description: Run mobile E2E tests (integration tests)
    run: dart test/mobile_e2e/run_mobile_e2e_tests.dart
    exec:
      failFast: true
    packageFilters:
      flutter: true
  
  test:all:
    description: Run all tests in the monorepo
    run: |
      echo "Running Dart tests..."
      melos run test:melos:dart || echo "No Dart-only packages with tests"
      echo "Running Flutter tests..."
      melos run test:melos:flutter || echo "No Flutter packages with tests"
      echo "Running Mobile E2E tests..."
      melos run test:mobile:e2e || echo "Mobile E2E tests not available"
  
  format:
    run: dart format --set-exit-if-changed .
    exec:
      failFast: true
  
  build:flutter:
    run: flutter build apk
    packageFilters:
      flutter: true
  
  clean:
    run: flutter clean && dart pub get
    exec:
      failFast: true

  coverage:
    run: dart test --coverage=coverage && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib
    exec:
      failFast: true

  deps:get:
    run: dart pub get
    exec:
      failFast: true

  deps:upgrade:
    run: dart pub upgrade
    exec:
      failFast: true
