// Mocks generated by Mockito
// Manually created mock for MqttClientInterface

import 'package:mockito/mockito.dart';
import 'package:merkle_kv_core/src/mqtt/mqtt_client_interface.dart';

class MockMqttClientInterface extends Mock implements MqttClientInterface {}