// Mocks generated by Mockito
// Manually created mock for StorageInterface and MqttClientInterface

import 'package:mockito/mockito.dart';
import 'package:merkle_kv_core/src/storage/storage_interface.dart';
import 'package:merkle_kv_core/src/mqtt/mqtt_client_interface.dart';

class MockStorageInterface extends Mock implements StorageInterface {}
class MockMqttClientInterface extends Mock implements MqttClientInterface {}