name: merkle_kv_core
description: Core implementation of MerkleKV Mobile - a distributed key-value store for mobile devices
version: 1.0.0
repository: https://github.com/mico220706/MerkleKV-Mobile
issue_tracker: https://github.com/mico220706/MerkleKV-Mobile/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  cbor: ^6.0.0
  uuid: ^4.0.0
  logging: ^1.2.0
  mqtt_client: ^10.0.0
  path: ^1.8.3
  meta: ^1.9.1
  collection: ^1.17.2
  rxdart: ^0.27.7

dev_dependencies:
  test: ^1.24.6
  mockito: ^5.4.2
  build_runner: ^2.4.6
  mocktail: ^1.0.0
  fake_async: ^1.3.1
  coverage: ^1.7.0

topics:
  - distributed-systems
  - key-value-store
  - mqtt
  - mobile
  - dart

false_secrets:
  - /test/**
