// Mocks generated by Mockito
// Manually created mock for MqttServerClient

import 'package:mockito/mockito.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

class MockMqttServerClient extends Mock implements MqttServerClient {}