name: Tests
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        working-directory: packages/merkle_kv_core
        run: dart pub get
      - name: Analyze code
        working-directory: packages/merkle_kv_core
        run: dart analyze
      - name: Run unit tests
        working-directory: packages/merkle_kv_core
        run: dart test --reporter=expanded --timeout=30s

  integration:
    runs-on: ubuntu-latest
    services:
      mosquitto:
        image: eclipse-mosquitto:2
        ports: ['1883:1883']
    env:
      MQTT_HOST: 127.0.0.1
      MQTT_PORT: 1883
      IT_REQUIRE_BROKER: '1'   # enforce execution; do not allow skip in CI
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - name: Get dependencies
        working-directory: packages/merkle_kv_core
        run: dart pub get
      - name: Run integration tests
        working-directory: packages/merkle_kv_core
        run: dart test -t integration --timeout=90s --chain-stack-traces
