name: Tests
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart analyze
      - name: Run unit tests
        run: dart test -x integration --reporter=expanded --timeout=30s

  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    env:
      MQTT_HOST: 127.0.0.1
      MQTT_PORT: 1883
      IT_REQUIRE_BROKER: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Start Mosquitto broker
        run: |
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v ${{ github.workspace }}/.ci/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2
          # Wait for Mosquitto to be ready
          for i in {1..30}; do
            if nc -z 127.0.0.1 1883; then
              echo "Mosquitto is ready"
              break
            fi
            echo "Waiting for Mosquitto... ($i/30)"
            sleep 1
          done
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - name: Run integration tests
        run: dart test -t integration --reporter=expanded --timeout=90s --chain-stack-traces