name: Tests
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart analyze
      - run: dart test -x integration --reporter=expanded --timeout=30s

  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    env:
      MQTT_HOST: 127.0.0.1
      MQTT_PORT: 1883
      IT_REQUIRE_BROKER: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Start Mosquitto broker
        run: |
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v ${{ github.workspace }}/.ci/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test -t integration --timeout=90s --chain-stack-traces