name: Tests
on: [push, pull_request]

jobs:
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    steps:
      - uses: actions/checkout@v4
      - name: Install Dart SDK from archive (bypass corrupted hostedtoolcache)
        run: |
          # Remove any existing Dart installations
          sudo rm -rf /opt/hostedtoolcache/dart
          rm -rf ~/.dart
          rm -rf ~/.pub-cache
          
          # Download and install Dart SDK directly
          wget -qO- https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip > dart-sdk.zip
          unzip -q dart-sdk.zip
          sudo mv dart-sdk /opt/dart
          
          # Add to PATH
          echo "/opt/dart/bin" >> $GITHUB_PATH
          export PATH="/opt/dart/bin:$PATH"
          
          # Verify installation
          dart --version
      - run: dart pub get
      - run: dart analyze
      - name: Run unit tests
        run: dart test -x integration --reporter=expanded --timeout=30s

  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/merkle_kv_core
    env:
      MQTT_HOST: 127.0.0.1
      MQTT_PORT: 1883
      IT_REQUIRE_BROKER: '1'
    steps:
      - uses: actions/checkout@v4
      - name: Start Mosquitto broker
        run: |
          docker run -d \
            --name mosquitto \
            -p 1883:1883 \
            -v ${{ github.workspace }}/.ci/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf \
            eclipse-mosquitto:2
          # Wait for Mosquitto to be ready
          for i in {1..30}; do
            if nc -z 127.0.0.1 1883; then
              echo "Mosquitto is ready"
              break
            fi
            echo "Waiting for Mosquitto... ($i/30)"
            sleep 1
          done
      - name: Install Dart SDK from archive (bypass corrupted hostedtoolcache)
        run: |
          # Remove any existing Dart installations
          sudo rm -rf /opt/hostedtoolcache/dart
          rm -rf ~/.dart
          rm -rf ~/.pub-cache
          
          # Download and install Dart SDK directly
          wget -qO- https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip > dart-sdk.zip
          unzip -q dart-sdk.zip
          sudo mv dart-sdk /opt/dart
          
          # Add to PATH
          echo "/opt/dart/bin" >> $GITHUB_PATH
          export PATH="/opt/dart/bin:$PATH"
          
          # Verify installation
          dart --version
      - run: dart pub get
      - name: Run integration tests
        run: |
          dart test test/replication/integration_test.dart --reporter=expanded --timeout=90s --chain-stack-traces
          dart test test/replication/event_publisher_integration_test.dart --reporter=expanded --timeout=90s --chain-stack-traces
          dart test test/commands/integration_test.dart --reporter=expanded --timeout=90s --chain-stack-traces